libs:
    autospec:
    base:
    formats:
    layouts:
    constructives:
    controls:
    portal:
    ads:
    data:
    wiz:
blocks:
    constructives.snippet-meta: 1.1.0a
name: 'Демонстрация серпа'
