jBlock.import.icon =
{
    service:
    {
        serp:{
            color:'url(icon/service/color/serp.svg)',
            bw:'url(icon/service/bw/serp.svg)'
        },
        images:{
            color:'url(icon/service/color/images.svg)',
            bw:'url(icon/service/bw/images.svg)'
        },
        maps:{
            color:'url(icon/service/color/maps.svg)',
            bw:'url(icon/service/bw/maps.svg)'
        },
        traffic:{
            color:'url(icon/service/color/traffic.svg)',
            bw:'url(icon/service/bw/traffic.svg)'
        },
        market:{
            color:'url(icon/service/color/market.svg)',
            bw:'url(icon/service/bw/market.svg)'
        },
        news:{
            color:'url(icon/service/color/news.svg)',
            bw:'url(icon/service/bw/news.svg)'
        },
        dict:{
            color:'url(icon/service/color/dict.svg)',
            bw:'url(icon/service/bw/dict.svg)'
        },
        video:{
            color:'url(icon/service/color/video.svg)',
            bw:'url(icon/service/bw/video.svg)'
        },
        weather:{
            color:'url(icon/service/color/weather.svg)',
            bw:'url(icon/service/bw/weather.svg)'
        },
        auto:{
            color:'url(icon/service/color/auto.svg)',
            bw:'url(icon/service/bw/auto.svg)'
        },
        music:{
            color:'url(icon/service/color/music.svg)',
            bw:'url(icon/service/bw/music.svg)'
        },
        afisha:{
            color:'url(icon/service/color/afisha.svg)',
            bw:'url(icon/service/bw/afisha.svg)'
        },
        translate:{
            color:'url(icon/service/color/translate.svg)',
            bw:'url(icon/service/bw/translate.svg)'
        },
        avia:{
            color:'url(icon/service/color/avia.svg)',
            bw:'url(icon/service/bw/avia.svg)'
        },
        timetable:{
            color:'url(icon/service/color/timetable.svg)',
            bw:'url(icon/service/bw/timetable.svg)'
        },
        taxi:{
            color:'url(icon/service/color/taxi.svg)',
            bw:'url(icon/service/bw/taxi.svg)'
        },
        tv:{
            color:'url(icon/service/color/tv.svg)',
            bw:'url(icon/service/bw/tv.svg)'
        },
        mail:{
            color:'url(icon/service/color/mail.svg)',
            bw:'url(icon/service/bw/mail.svg)'
        },
        disk:{
            color:'url(icon/service/color/disk.svg)',
            bw:'url(icon/service/bw/disk.svg)'
        },
        sport:{
            color:'url(icon/service/color/serp.svg)',
            bw:'url(icon/service/bw/serp.svg)'
        },
        app:{
            color:'url(icon/service/color/app.svg)',
            bw:'url(icon/service/bw/app.svg)'
        },
        job:{
            color:'url(icon/service/color/job.svg)',
            bw:'url(icon/service/bw/job.svg)'
        },
        money:{
            color:'url(icon/service/color/money.svg)',
            bw:'url(icon/service/bw/money.svg)'
        },
    }
}
;